// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateMerchantAddressRequest create merchant address request
//
// swagger:model createMerchantAddressRequest
type CreateMerchantAddressRequest struct {

	// address
	// Example: 0xdc22Bb64132fB03467910fc49595F08fCf5C241b
	// Required: true
	// Max Length: 128
	Address string `json:"address"`

	// blockchain
	// Example: ETH
	// Required: true
	// Enum: [BTC ETH TRON MATIC BSC]
	Blockchain string `json:"blockchain"`

	// Name
	// Example: My Wallet
	// Required: true
	// Max Length: 128
	// Min Length: 2
	Name string `json:"name"`
}

// Validate validates this create merchant address request
func (m *CreateMerchantAddressRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBlockchain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateMerchantAddressRequest) validateAddress(formats strfmt.Registry) error {

	if err := validate.RequiredString("address", "body", m.Address); err != nil {
		return err
	}

	if err := validate.MaxLength("address", "body", m.Address, 128); err != nil {
		return err
	}

	return nil
}

var createMerchantAddressRequestTypeBlockchainPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["BTC","ETH","TRON","MATIC","BSC"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createMerchantAddressRequestTypeBlockchainPropEnum = append(createMerchantAddressRequestTypeBlockchainPropEnum, v)
	}
}

const (

	// CreateMerchantAddressRequestBlockchainBTC captures enum value "BTC"
	CreateMerchantAddressRequestBlockchainBTC string = "BTC"

	// CreateMerchantAddressRequestBlockchainETH captures enum value "ETH"
	CreateMerchantAddressRequestBlockchainETH string = "ETH"

	// CreateMerchantAddressRequestBlockchainTRON captures enum value "TRON"
	CreateMerchantAddressRequestBlockchainTRON string = "TRON"

	// CreateMerchantAddressRequestBlockchainMATIC captures enum value "MATIC"
	CreateMerchantAddressRequestBlockchainMATIC string = "MATIC"

	// CreateMerchantAddressRequestBlockchainBSC captures enum value "BSC"
	CreateMerchantAddressRequestBlockchainBSC string = "BSC"
)

// prop value enum
func (m *CreateMerchantAddressRequest) validateBlockchainEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, createMerchantAddressRequestTypeBlockchainPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateMerchantAddressRequest) validateBlockchain(formats strfmt.Registry) error {

	if err := validate.RequiredString("blockchain", "body", m.Blockchain); err != nil {
		return err
	}

	// value enum
	if err := m.validateBlockchainEnum("blockchain", "body", m.Blockchain); err != nil {
		return err
	}

	return nil
}

func (m *CreateMerchantAddressRequest) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", m.Name, 2); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", m.Name, 128); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create merchant address request based on context it is used
func (m *CreateMerchantAddressRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateMerchantAddressRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateMerchantAddressRequest) UnmarshalBinary(b []byte) error {
	var res CreateMerchantAddressRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
