// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MerchantListItem merchant list item
//
// swagger:model merchantListItem
type MerchantListItem struct {

	// merchant UUID
	// Example: 1eb5fbb5-ece0-475c-9ddd-23c524a33e06
	ID string `json:"id,omitempty"`

	// Name
	// Example: My Store
	Name string `json:"name,omitempty"`

	// Website URL
	// Example: https://my-store.com
	Website string `json:"website,omitempty"`
}

// Validate validates this merchant list item
func (m *MerchantListItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this merchant list item based on context it is used
func (m *MerchantListItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MerchantListItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MerchantListItem) UnmarshalBinary(b []byte) error {
	var res MerchantListItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
