// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PaymentLink Payment Link object
//
// swagger:model paymentLink
type PaymentLink struct {

	// Created At timestamp
	// Example: 2022-11-23 19:49:21.386201 +0000 UTC
	// Required: true
	// Format: datetime
	CreatedAt strfmt.DateTime `json:"createdAt"`

	// Fiat ticker for payment template.
	// Required: true
	// Enum: [USD EUR]
	Currency string `json:"currency"`

	// Optional payment description visible for a customer in payment screen
	// Example: White T-shirt size M
	Description *string `json:"description"`

	// Link's UUID
	// Example: 123e4567-e89b-12d3-a456-426655440000
	// Required: true
	ID string `json:"id"`

	// Name
	// Example: My Link
	// Required: true
	Name string `json:"name"`

	// Payment price
	// Example: 29.9
	// Required: true
	Price string `json:"price"`

	// Redirect URL after successful customer's payment
	// Example: https://my-site.com/success?order=abc123
	RedirectURL *string `json:"redirectUrl"`

	// Action type after OxygenPay receives incoming payment from a customer.
	// - `redirectUrl` displays "Back to site" button with provided .redirectUrl.
	// - `showMessage` displays "Show message" with content provided in .successMessage.
	//
	// Required: true
	// Enum: [redirect showMessage]
	SuccessAction string `json:"successAction"`

	// message after successful customer's payment
	SuccessMessage *string `json:"successMessage"`

	// Link's URL
	// Example: https://pay.o2pay.co/link/ufaiCu6J
	// Required: true
	URL string `json:"url"`
}

// Validate validates this payment link
func (m *PaymentLink) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurrency(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSuccessAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PaymentLink) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("createdAt", "body", strfmt.DateTime(m.CreatedAt)); err != nil {
		return err
	}

	if err := validate.FormatOf("createdAt", "body", "datetime", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var paymentLinkTypeCurrencyPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["USD","EUR"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		paymentLinkTypeCurrencyPropEnum = append(paymentLinkTypeCurrencyPropEnum, v)
	}
}

const (

	// PaymentLinkCurrencyUSD captures enum value "USD"
	PaymentLinkCurrencyUSD string = "USD"

	// PaymentLinkCurrencyEUR captures enum value "EUR"
	PaymentLinkCurrencyEUR string = "EUR"
)

// prop value enum
func (m *PaymentLink) validateCurrencyEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, paymentLinkTypeCurrencyPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PaymentLink) validateCurrency(formats strfmt.Registry) error {

	if err := validate.RequiredString("currency", "body", m.Currency); err != nil {
		return err
	}

	// value enum
	if err := m.validateCurrencyEnum("currency", "body", m.Currency); err != nil {
		return err
	}

	return nil
}

func (m *PaymentLink) validateID(formats strfmt.Registry) error {

	if err := validate.RequiredString("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *PaymentLink) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *PaymentLink) validatePrice(formats strfmt.Registry) error {

	if err := validate.RequiredString("price", "body", m.Price); err != nil {
		return err
	}

	return nil
}

var paymentLinkTypeSuccessActionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["redirect","showMessage"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		paymentLinkTypeSuccessActionPropEnum = append(paymentLinkTypeSuccessActionPropEnum, v)
	}
}

const (

	// PaymentLinkSuccessActionRedirect captures enum value "redirect"
	PaymentLinkSuccessActionRedirect string = "redirect"

	// PaymentLinkSuccessActionShowMessage captures enum value "showMessage"
	PaymentLinkSuccessActionShowMessage string = "showMessage"
)

// prop value enum
func (m *PaymentLink) validateSuccessActionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, paymentLinkTypeSuccessActionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PaymentLink) validateSuccessAction(formats strfmt.Registry) error {

	if err := validate.RequiredString("successAction", "body", m.SuccessAction); err != nil {
		return err
	}

	// value enum
	if err := m.validateSuccessActionEnum("successAction", "body", m.SuccessAction); err != nil {
		return err
	}

	return nil
}

func (m *PaymentLink) validateURL(formats strfmt.Registry) error {

	if err := validate.RequiredString("url", "body", m.URL); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this payment link based on context it is used
func (m *PaymentLink) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentLink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentLink) UnmarshalBinary(b []byte) error {
	var res PaymentLink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
