// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SupportedPaymentMethod PaymentType
//
// swagger:model supportedPaymentMethod
type SupportedPaymentMethod struct {

	// Blockchain ticker
	// Example: ETH
	Blockchain string `json:"blockchain"`

	// blockchain name
	// Example: Ethereum
	BlockchainName string `json:"blockchainName"`

	// Display Name
	// Example: USDT (Ethereum)
	DisplayName string `json:"displayName"`

	// enabled
	// Example: true
	Enabled bool `json:"enabled"`

	// Coin / Token Name
	// Example: USDT
	Name string `json:"name"`

	// ticker
	// Example: ETH_USDT
	Ticker string `json:"ticker"`
}

// Validate validates this supported payment method
func (m *SupportedPaymentMethod) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this supported payment method based on context it is used
func (m *SupportedPaymentMethod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SupportedPaymentMethod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SupportedPaymentMethod) UnmarshalBinary(b []byte) error {
	var res SupportedPaymentMethod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
