// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Withdrawal withdrawal
//
// swagger:model withdrawal
type Withdrawal struct {

	// Payment UUID
	// Example: A9B04890-7FB9-42C6-A63B-9163968E4580
	PaymentID string `json:"paymentId,omitempty"`
}

// Validate validates this withdrawal
func (m *Withdrawal) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this withdrawal based on context it is used
func (m *Withdrawal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Withdrawal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Withdrawal) UnmarshalBinary(b []byte) error {
	var res Withdrawal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
