// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/oxygenpay/oxygen/pkg/api-kms/v1/model"
)

// NewCreateMaticTransactionParams creates a new CreateMaticTransactionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateMaticTransactionParams() *CreateMaticTransactionParams {
	return &CreateMaticTransactionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateMaticTransactionParamsWithTimeout creates a new CreateMaticTransactionParams object
// with the ability to set a timeout on a request.
func NewCreateMaticTransactionParamsWithTimeout(timeout time.Duration) *CreateMaticTransactionParams {
	return &CreateMaticTransactionParams{
		timeout: timeout,
	}
}

// NewCreateMaticTransactionParamsWithContext creates a new CreateMaticTransactionParams object
// with the ability to set a context for a request.
func NewCreateMaticTransactionParamsWithContext(ctx context.Context) *CreateMaticTransactionParams {
	return &CreateMaticTransactionParams{
		Context: ctx,
	}
}

// NewCreateMaticTransactionParamsWithHTTPClient creates a new CreateMaticTransactionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateMaticTransactionParamsWithHTTPClient(client *http.Client) *CreateMaticTransactionParams {
	return &CreateMaticTransactionParams{
		HTTPClient: client,
	}
}

/* CreateMaticTransactionParams contains all the parameters to send to the API endpoint
   for the create matic transaction operation.

   Typically these are written to a http.Request.
*/
type CreateMaticTransactionParams struct {

	// Data.
	Data *model.CreateMaticTransactionRequest

	/* WalletID.

	   Wallet UUID
	*/
	WalletID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create matic transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMaticTransactionParams) WithDefaults() *CreateMaticTransactionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create matic transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateMaticTransactionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create matic transaction params
func (o *CreateMaticTransactionParams) WithTimeout(timeout time.Duration) *CreateMaticTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create matic transaction params
func (o *CreateMaticTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create matic transaction params
func (o *CreateMaticTransactionParams) WithContext(ctx context.Context) *CreateMaticTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create matic transaction params
func (o *CreateMaticTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create matic transaction params
func (o *CreateMaticTransactionParams) WithHTTPClient(client *http.Client) *CreateMaticTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create matic transaction params
func (o *CreateMaticTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the create matic transaction params
func (o *CreateMaticTransactionParams) WithData(data *model.CreateMaticTransactionRequest) *CreateMaticTransactionParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create matic transaction params
func (o *CreateMaticTransactionParams) SetData(data *model.CreateMaticTransactionRequest) {
	o.Data = data
}

// WithWalletID adds the walletID to the create matic transaction params
func (o *CreateMaticTransactionParams) WithWalletID(walletID string) *CreateMaticTransactionParams {
	o.SetWalletID(walletID)
	return o
}

// SetWalletID adds the walletId to the create matic transaction params
func (o *CreateMaticTransactionParams) SetWalletID(walletID string) {
	o.WalletID = walletID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateMaticTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param walletId
	if err := r.SetPathParam("walletId", o.WalletID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
