// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/oxygenpay/oxygen/pkg/api-kms/v1/model"
)

// CreateWalletReader is a Reader for the CreateWallet structure.
type CreateWalletReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateWalletReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateWalletCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateWalletBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateWalletCreated creates a CreateWalletCreated with default headers values
func NewCreateWalletCreated() *CreateWalletCreated {
	return &CreateWalletCreated{}
}

/* CreateWalletCreated describes a response with status code 201, with default header values.

Wallet created
*/
type CreateWalletCreated struct {
	Payload *model.Wallet
}

func (o *CreateWalletCreated) Error() string {
	return fmt.Sprintf("[POST /wallet][%d] createWalletCreated  %+v", 201, o.Payload)
}
func (o *CreateWalletCreated) GetPayload() *model.Wallet {
	return o.Payload
}

func (o *CreateWalletCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Wallet)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateWalletBadRequest creates a CreateWalletBadRequest with default headers values
func NewCreateWalletBadRequest() *CreateWalletBadRequest {
	return &CreateWalletBadRequest{}
}

/* CreateWalletBadRequest describes a response with status code 400, with default header values.

Validation error
*/
type CreateWalletBadRequest struct {
	Payload *model.ErrorResponse
}

func (o *CreateWalletBadRequest) Error() string {
	return fmt.Sprintf("[POST /wallet][%d] createWalletBadRequest  %+v", 400, o.Payload)
}
func (o *CreateWalletBadRequest) GetPayload() *model.ErrorResponse {
	return o.Payload
}

func (o *CreateWalletBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
