// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/oxygenpay/oxygen/pkg/api-kms/v1/model"
)

// NewCreateBSCTransactionParams creates a new CreateBSCTransactionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateBSCTransactionParams() *CreateBSCTransactionParams {
	return &CreateBSCTransactionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBSCTransactionParamsWithTimeout creates a new CreateBSCTransactionParams object
// with the ability to set a timeout on a request.
func NewCreateBSCTransactionParamsWithTimeout(timeout time.Duration) *CreateBSCTransactionParams {
	return &CreateBSCTransactionParams{
		timeout: timeout,
	}
}

// NewCreateBSCTransactionParamsWithContext creates a new CreateBSCTransactionParams object
// with the ability to set a context for a request.
func NewCreateBSCTransactionParamsWithContext(ctx context.Context) *CreateBSCTransactionParams {
	return &CreateBSCTransactionParams{
		Context: ctx,
	}
}

// NewCreateBSCTransactionParamsWithHTTPClient creates a new CreateBSCTransactionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateBSCTransactionParamsWithHTTPClient(client *http.Client) *CreateBSCTransactionParams {
	return &CreateBSCTransactionParams{
		HTTPClient: client,
	}
}

/* CreateBSCTransactionParams contains all the parameters to send to the API endpoint
   for the create b s c transaction operation.

   Typically these are written to a http.Request.
*/
type CreateBSCTransactionParams struct {

	// Data.
	Data *model.CreateBSCTransactionRequest

	/* WalletID.

	   Wallet UUID
	*/
	WalletID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create b s c transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBSCTransactionParams) WithDefaults() *CreateBSCTransactionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create b s c transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateBSCTransactionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create b s c transaction params
func (o *CreateBSCTransactionParams) WithTimeout(timeout time.Duration) *CreateBSCTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create b s c transaction params
func (o *CreateBSCTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create b s c transaction params
func (o *CreateBSCTransactionParams) WithContext(ctx context.Context) *CreateBSCTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create b s c transaction params
func (o *CreateBSCTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create b s c transaction params
func (o *CreateBSCTransactionParams) WithHTTPClient(client *http.Client) *CreateBSCTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create b s c transaction params
func (o *CreateBSCTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the create b s c transaction params
func (o *CreateBSCTransactionParams) WithData(data *model.CreateBSCTransactionRequest) *CreateBSCTransactionParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create b s c transaction params
func (o *CreateBSCTransactionParams) SetData(data *model.CreateBSCTransactionRequest) {
	o.Data = data
}

// WithWalletID adds the walletID to the create b s c transaction params
func (o *CreateBSCTransactionParams) WithWalletID(walletID string) *CreateBSCTransactionParams {
	o.SetWalletID(walletID)
	return o
}

// SetWalletID adds the walletId to the create b s c transaction params
func (o *CreateBSCTransactionParams) SetWalletID(walletID string) {
	o.WalletID = walletID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBSCTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param walletId
	if err := r.SetPathParam("walletId", o.WalletID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
