// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/oxygenpay/oxygen/pkg/api-kms/v1/model"
)

// NewCreateEthereumTransactionParams creates a new CreateEthereumTransactionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateEthereumTransactionParams() *CreateEthereumTransactionParams {
	return &CreateEthereumTransactionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateEthereumTransactionParamsWithTimeout creates a new CreateEthereumTransactionParams object
// with the ability to set a timeout on a request.
func NewCreateEthereumTransactionParamsWithTimeout(timeout time.Duration) *CreateEthereumTransactionParams {
	return &CreateEthereumTransactionParams{
		timeout: timeout,
	}
}

// NewCreateEthereumTransactionParamsWithContext creates a new CreateEthereumTransactionParams object
// with the ability to set a context for a request.
func NewCreateEthereumTransactionParamsWithContext(ctx context.Context) *CreateEthereumTransactionParams {
	return &CreateEthereumTransactionParams{
		Context: ctx,
	}
}

// NewCreateEthereumTransactionParamsWithHTTPClient creates a new CreateEthereumTransactionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateEthereumTransactionParamsWithHTTPClient(client *http.Client) *CreateEthereumTransactionParams {
	return &CreateEthereumTransactionParams{
		HTTPClient: client,
	}
}

/* CreateEthereumTransactionParams contains all the parameters to send to the API endpoint
   for the create ethereum transaction operation.

   Typically these are written to a http.Request.
*/
type CreateEthereumTransactionParams struct {

	// Data.
	Data *model.CreateEthereumTransactionRequest

	/* WalletID.

	   Wallet UUID
	*/
	WalletID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create ethereum transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateEthereumTransactionParams) WithDefaults() *CreateEthereumTransactionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create ethereum transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateEthereumTransactionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create ethereum transaction params
func (o *CreateEthereumTransactionParams) WithTimeout(timeout time.Duration) *CreateEthereumTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create ethereum transaction params
func (o *CreateEthereumTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create ethereum transaction params
func (o *CreateEthereumTransactionParams) WithContext(ctx context.Context) *CreateEthereumTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create ethereum transaction params
func (o *CreateEthereumTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create ethereum transaction params
func (o *CreateEthereumTransactionParams) WithHTTPClient(client *http.Client) *CreateEthereumTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create ethereum transaction params
func (o *CreateEthereumTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the create ethereum transaction params
func (o *CreateEthereumTransactionParams) WithData(data *model.CreateEthereumTransactionRequest) *CreateEthereumTransactionParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create ethereum transaction params
func (o *CreateEthereumTransactionParams) SetData(data *model.CreateEthereumTransactionRequest) {
	o.Data = data
}

// WithWalletID adds the walletID to the create ethereum transaction params
func (o *CreateEthereumTransactionParams) WithWalletID(walletID string) *CreateEthereumTransactionParams {
	o.SetWalletID(walletID)
	return o
}

// SetWalletID adds the walletId to the create ethereum transaction params
func (o *CreateEthereumTransactionParams) SetWalletID(walletID string) {
	o.WalletID = walletID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateEthereumTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param walletId
	if err := r.SetPathParam("walletId", o.WalletID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
