// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/oxygenpay/oxygen/pkg/api-kms/v1/model"
)

// CreateBSCTransactionReader is a Reader for the CreateBSCTransaction structure.
type CreateBSCTransactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateBSCTransactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateBSCTransactionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateBSCTransactionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateBSCTransactionCreated creates a CreateBSCTransactionCreated with default headers values
func NewCreateBSCTransactionCreated() *CreateBSCTransactionCreated {
	return &CreateBSCTransactionCreated{}
}

/* CreateBSCTransactionCreated describes a response with status code 201, with default header values.

Transaction Created
*/
type CreateBSCTransactionCreated struct {
	Payload *model.BSCTransaction
}

func (o *CreateBSCTransactionCreated) Error() string {
	return fmt.Sprintf("[POST /wallet/{walletId}/transaction/bsc][%d] createBSCTransactionCreated  %+v", 201, o.Payload)
}
func (o *CreateBSCTransactionCreated) GetPayload() *model.BSCTransaction {
	return o.Payload
}

func (o *CreateBSCTransactionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.BSCTransaction)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateBSCTransactionBadRequest creates a CreateBSCTransactionBadRequest with default headers values
func NewCreateBSCTransactionBadRequest() *CreateBSCTransactionBadRequest {
	return &CreateBSCTransactionBadRequest{}
}

/* CreateBSCTransactionBadRequest describes a response with status code 400, with default header values.

Validation error / Not found
*/
type CreateBSCTransactionBadRequest struct {
	Payload *model.ErrorResponse
}

func (o *CreateBSCTransactionBadRequest) Error() string {
	return fmt.Sprintf("[POST /wallet/{walletId}/transaction/bsc][%d] createBSCTransactionBadRequest  %+v", 400, o.Payload)
}
func (o *CreateBSCTransactionBadRequest) GetPayload() *model.ErrorResponse {
	return o.Payload
}

func (o *CreateBSCTransactionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
