// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/oxygenpay/oxygen/pkg/api-kms/v1/model"
)

// NewCreateWalletParams creates a new CreateWalletParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateWalletParams() *CreateWalletParams {
	return &CreateWalletParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateWalletParamsWithTimeout creates a new CreateWalletParams object
// with the ability to set a timeout on a request.
func NewCreateWalletParamsWithTimeout(timeout time.Duration) *CreateWalletParams {
	return &CreateWalletParams{
		timeout: timeout,
	}
}

// NewCreateWalletParamsWithContext creates a new CreateWalletParams object
// with the ability to set a context for a request.
func NewCreateWalletParamsWithContext(ctx context.Context) *CreateWalletParams {
	return &CreateWalletParams{
		Context: ctx,
	}
}

// NewCreateWalletParamsWithHTTPClient creates a new CreateWalletParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateWalletParamsWithHTTPClient(client *http.Client) *CreateWalletParams {
	return &CreateWalletParams{
		HTTPClient: client,
	}
}

/* CreateWalletParams contains all the parameters to send to the API endpoint
   for the create wallet operation.

   Typically these are written to a http.Request.
*/
type CreateWalletParams struct {

	// Data.
	Data *model.CreateWalletRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create wallet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateWalletParams) WithDefaults() *CreateWalletParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create wallet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateWalletParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create wallet params
func (o *CreateWalletParams) WithTimeout(timeout time.Duration) *CreateWalletParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create wallet params
func (o *CreateWalletParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create wallet params
func (o *CreateWalletParams) WithContext(ctx context.Context) *CreateWalletParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create wallet params
func (o *CreateWalletParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create wallet params
func (o *CreateWalletParams) WithHTTPClient(client *http.Client) *CreateWalletParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create wallet params
func (o *CreateWalletParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the create wallet params
func (o *CreateWalletParams) WithData(data *model.CreateWalletRequest) *CreateWalletParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create wallet params
func (o *CreateWalletParams) SetData(data *model.CreateWalletRequest) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *CreateWalletParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
