// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteWalletParams creates a new DeleteWalletParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteWalletParams() *DeleteWalletParams {
	return &DeleteWalletParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteWalletParamsWithTimeout creates a new DeleteWalletParams object
// with the ability to set a timeout on a request.
func NewDeleteWalletParamsWithTimeout(timeout time.Duration) *DeleteWalletParams {
	return &DeleteWalletParams{
		timeout: timeout,
	}
}

// NewDeleteWalletParamsWithContext creates a new DeleteWalletParams object
// with the ability to set a context for a request.
func NewDeleteWalletParamsWithContext(ctx context.Context) *DeleteWalletParams {
	return &DeleteWalletParams{
		Context: ctx,
	}
}

// NewDeleteWalletParamsWithHTTPClient creates a new DeleteWalletParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteWalletParamsWithHTTPClient(client *http.Client) *DeleteWalletParams {
	return &DeleteWalletParams{
		HTTPClient: client,
	}
}

/* DeleteWalletParams contains all the parameters to send to the API endpoint
   for the delete wallet operation.

   Typically these are written to a http.Request.
*/
type DeleteWalletParams struct {

	/* WalletID.

	   Wallet UUID
	*/
	WalletID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete wallet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteWalletParams) WithDefaults() *DeleteWalletParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete wallet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteWalletParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete wallet params
func (o *DeleteWalletParams) WithTimeout(timeout time.Duration) *DeleteWalletParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete wallet params
func (o *DeleteWalletParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete wallet params
func (o *DeleteWalletParams) WithContext(ctx context.Context) *DeleteWalletParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete wallet params
func (o *DeleteWalletParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete wallet params
func (o *DeleteWalletParams) WithHTTPClient(client *http.Client) *DeleteWalletParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete wallet params
func (o *DeleteWalletParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWalletID adds the walletID to the delete wallet params
func (o *DeleteWalletParams) WithWalletID(walletID string) *DeleteWalletParams {
	o.SetWalletID(walletID)
	return o
}

// SetWalletID adds the walletId to the delete wallet params
func (o *DeleteWalletParams) SetWalletID(walletID string) {
	o.WalletID = walletID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteWalletParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param walletId
	if err := r.SetPathParam("walletId", o.WalletID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
