// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: locks.sql

package repository

import (
	"context"
)

const advisoryTxLock = `-- name: AdvisoryTxLock :exec
select pg_advisory_xact_lock($1)
`

func (q *Queries) AdvisoryTxLock(ctx context.Context, pgAdvisoryXactLock int64) error {
	_, err := q.db.Exec(ctx, advisoryTxLock, pgAdvisoryXactLock)
	return err
}
