// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type ApiToken struct {
	ID         int64
	EntityType string
	EntityID   int64
	CreatedAt  time.Time
	Token      string
	Name       sql.NullString
	Settings   pgtype.JSONB
	Uuid       uuid.UUID
}

type Balance struct {
	ID           int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	EntityID     int64
	EntityType   string
	Network      string
	NetworkID    string
	CurrencyType string
	Currency     string
	Decimals     int32
	Amount       pgtype.Numeric
	Uuid         uuid.NullUUID
}

type BalanceAuditLog struct {
	ID        int64
	CreatedAt time.Time
	BalanceID int64
	Comment   string
	Metadata  pgtype.JSONB
}

type Customer struct {
	ID         int64
	Uuid       uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Email      sql.NullString
	MerchantID int64
}

type JobLog struct {
	ID        int64
	CreatedAt time.Time
	Level     int16
	JobID     sql.NullString
	Message   string
	Metadata  pgtype.JSONB
}

type Merchant struct {
	ID        int64
	Uuid      uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	Name      string
	Website   string
	CreatorID int64
	Settings  pgtype.JSONB
}

type MerchantAddress struct {
	ID         int64
	Uuid       uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	MerchantID int64
	Name       string
	Blockchain string
	Address    string
}

type Payment struct {
	ID                int64
	PublicID          uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Type              string
	Status            string
	MerchantID        int64
	MerchantOrderUuid uuid.UUID
	MerchantOrderID   sql.NullString
	ExpiresAt         sql.NullTime
	Price             pgtype.Numeric
	Decimals          int32
	Currency          string
	Description       sql.NullString
	RedirectUrl       string
	CustomerID        sql.NullInt64
	IsTest            bool
	WebhookSentAt     sql.NullTime
	Metadata          pgtype.JSONB
}

type PaymentLink struct {
	ID             int64
	Uuid           uuid.UUID
	Slug           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	MerchantID     int64
	Name           string
	Description    string
	Price          pgtype.Numeric
	Decimals       int32
	Currency       string
	SuccessAction  string
	RedirectUrl    sql.NullString
	SuccessMessage sql.NullString
	IsTest         bool
}

type Registry struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	MerchantID  int64
	Key         string
	Value       string
	Description string
}

type Transaction struct {
	ID                int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	MerchantID        int64
	Status            string
	Type              string
	EntityID          sql.NullInt64
	RecipientWalletID sql.NullInt64
	SenderAddress     sql.NullString
	RecipientAddress  string
	TransactionHash   sql.NullString
	Blockchain        string
	CurrencyType      string
	Currency          string
	Decimals          int32
	Amount            pgtype.Numeric
	FactAmount        pgtype.Numeric
	NetworkFee        pgtype.Numeric
	ServiceFee        pgtype.Numeric
	UsdAmount         pgtype.Numeric
	Metadata          pgtype.JSONB
	NetworkID         sql.NullString
	IsTest            bool
	NetworkDecimals   int32
	SenderWalletID    sql.NullInt64
}

type User struct {
	ID              int64
	Name            string
	Email           string
	Uuid            uuid.UUID
	GoogleID        sql.NullString
	ProfileImageUrl sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
	Settings        pgtype.JSONB
	Password        sql.NullString
}

type Wallet struct {
	ID                           int64
	CreatedAt                    time.Time
	Uuid                         uuid.UUID
	Address                      string
	Blockchain                   string
	TatumMainnetSubscriptionID   sql.NullString
	TatumTestnetSubscriptionID   sql.NullString
	Type                         sql.NullString
	ConfirmedMainnetTransactions int64
	PendingMainnetTransactions   int64
	PendingTestnetTransactions   int64
	ConfirmedTestnetTransactions int64
}

type WalletLock struct {
	ID          int64
	WalletID    int64
	MerchantID  int64
	Currency    string
	NetworkID   string
	LockedAt    time.Time
	LockedUntil sql.NullTime
}
