// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TronTransaction Signed transaction.
// See https://developers.tron.network/reference/createtransaction
//
//
// swagger:model tronTransaction
type TronTransaction struct {

	// raw data
	RawData interface{} `json:"raw_data"`

	// raw data hex
	RawDataHex string `json:"raw_data_Hex"`

	// signature
	Signature []string `json:"signature"`

	// tx ID
	TxID string `json:"txID"`

	// visible
	Visible bool `json:"visible"`
}

// Validate validates this tron transaction
func (m *TronTransaction) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tron transaction based on context it is used
func (m *TronTransaction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TronTransaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TronTransaction) UnmarshalBinary(b []byte) error {
	var res TronTransaction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
