// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BroadcastTransactionRequest broadcast transaction request
//
// swagger:model broadcastTransactionRequest
type BroadcastTransactionRequest struct {

	// blockchain
	// Required: true
	Blockchain string `json:"blockchain"`

	// Raw hex-encoded transaction
	// Required: true
	Hex string `json:"hex"`

	// is test
	IsTest bool `json:"isTest,omitempty"`
}

// Validate validates this broadcast transaction request
func (m *BroadcastTransactionRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBlockchain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHex(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BroadcastTransactionRequest) validateBlockchain(formats strfmt.Registry) error {

	if err := validate.RequiredString("blockchain", "body", m.Blockchain); err != nil {
		return err
	}

	return nil
}

func (m *BroadcastTransactionRequest) validateHex(formats strfmt.Registry) error {

	if err := validate.RequiredString("hex", "body", m.Hex); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this broadcast transaction request based on context it is used
func (m *BroadcastTransactionRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BroadcastTransactionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BroadcastTransactionRequest) UnmarshalBinary(b []byte) error {
	var res BroadcastTransactionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
