// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BroadcastTransactionResponse broadcast transaction response
//
// swagger:model broadcastTransactionResponse
type BroadcastTransactionResponse struct {

	// transaction hash Id
	TransactionHashID string `json:"transactionHashId"`
}

// Validate validates this broadcast transaction response
func (m *BroadcastTransactionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this broadcast transaction response based on context it is used
func (m *BroadcastTransactionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BroadcastTransactionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BroadcastTransactionResponse) UnmarshalBinary(b []byte) error {
	var res BroadcastTransactionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
