// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateWalletRequest create wallet request
//
// swagger:model createWalletRequest
type CreateWalletRequest struct {

	// blockchain
	// Required: true
	Blockchain *Blockchain `json:"blockchain"`
}

// Validate validates this create wallet request
func (m *CreateWalletRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBlockchain(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateWalletRequest) validateBlockchain(formats strfmt.Registry) error {

	if err := validate.Required("blockchain", "body", m.Blockchain); err != nil {
		return err
	}

	if err := validate.Required("blockchain", "body", m.Blockchain); err != nil {
		return err
	}

	if m.Blockchain != nil {
		if err := m.Blockchain.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("blockchain")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create wallet request based on the context it is used
func (m *CreateWalletRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBlockchain(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateWalletRequest) contextValidateBlockchain(ctx context.Context, formats strfmt.Registry) error {

	if m.Blockchain != nil {
		if err := m.Blockchain.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("blockchain")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateWalletRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateWalletRequest) UnmarshalBinary(b []byte) error {
	var res CreateWalletRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
