// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RunJobRequest run job request
//
// swagger:model runJobRequest
type RunJobRequest struct {

	// job
	// Required: true
	Job string `json:"job"`
}

// Validate validates this run job request
func (m *RunJobRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJob(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RunJobRequest) validateJob(formats strfmt.Registry) error {

	if err := validate.RequiredString("job", "body", m.Job); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this run job request based on context it is used
func (m *RunJobRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RunJobRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RunJobRequest) UnmarshalBinary(b []byte) error {
	var res RunJobRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
