// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// CreatePaymentFromLinkRequest create payment from link request
//
// swagger:model createPaymentFromLinkRequest
type CreatePaymentFromLinkRequest interface{}
