// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreatePaymentMethodRequest create payment method request
//
// swagger:model createPaymentMethodRequest
type CreatePaymentMethodRequest struct {

	// Currency ticker
	// Example: ETH_USDT
	// Required: true
	Ticker string `json:"ticker"`
}

// Validate validates this create payment method request
func (m *CreatePaymentMethodRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTicker(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreatePaymentMethodRequest) validateTicker(formats strfmt.Registry) error {

	if err := validate.RequiredString("ticker", "body", m.Ticker); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create payment method request based on context it is used
func (m *CreatePaymentMethodRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreatePaymentMethodRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreatePaymentMethodRequest) UnmarshalBinary(b []byte) error {
	var res CreatePaymentMethodRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
