// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaymentMethod PaymentType
//
// swagger:model paymentMethod
type PaymentMethod struct {

	// blockchain
	Blockchain string `json:"blockchain"`

	// blockchain name
	BlockchainName string `json:"blockchainName"`

	// display name
	DisplayName string `json:"displayName"`

	// is test
	IsTest bool `json:"isTest"`

	// name
	Name string `json:"name"`

	// network Id
	NetworkID string `json:"networkId"`

	// ticker
	Ticker string `json:"ticker"`
}

// Validate validates this payment method
func (m *PaymentMethod) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this payment method based on context it is used
func (m *PaymentMethod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentMethod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentMethod) UnmarshalBinary(b []byte) error {
	var res PaymentMethod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
